spring:
  application:
    name: utility-tracker

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/utility_db
    username: postgres
    password: dima02wer
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
